const countries = [
    { name: 'Algeria', phoneCode: '+213', iso2Code: 'DZ' },
    { name: 'Angola', phoneCode: '+244', iso2Code: 'AO' },
    { name: 'Benin', phoneCode: '+229', iso2Code: 'BJ' },
    { name: 'Botswana', phoneCode: '+267', iso2Code: 'BW' },
    { name: 'Burkina Faso', phoneCode: '+226', iso2Code: 'BF' },
    { name: 'Burundi', phoneCode: '+257', iso2Code: 'BI' },
    { name: 'Cabo Verde', phoneCode: '+238', iso2Code: 'CV' },
    { name: 'Cameroon', phoneCode: '+237', iso2Code: 'CM' },
    { name: 'Central African Republic', phoneCode: '+236', iso2Code: 'CF' },
    { name: 'Chad', phoneCode: '+235', iso2Code: 'TD' },
    { name: 'Comoros', phoneCode: '+269', iso2Code: 'KM' },
    { name: 'Congo', phoneCode: '+242', iso2Code: 'CG' },
    { name: 'Democratic Republic of the Congo', phoneCode: '+243', iso2Code: 'CD' },
    { name: 'Djibouti', phoneCode: '+253', iso2Code: 'DJ' },
    { name: 'Egypt', phoneCode: '+20', iso2Code: 'EG' },
    { name: 'Equatorial Guinea', phoneCode: '+240', iso2Code: 'GQ' },
    { name: 'Eritrea', phoneCode: '+291', iso2Code: 'ER' },
    { name: 'Eswatini', phoneCode: '+268', iso2Code: 'SZ' },
    { name: 'Ethiopia', phoneCode: '+251', iso2Code: 'ET' },
    { name: 'Gabon', phoneCode: '+241', iso2Code: 'GA' },
    { name: 'Gambia', phoneCode: '+220', iso2Code: 'GM' },
    { name: 'Ghana', phoneCode: '+233', iso2Code: 'GH' },
    { name: 'Guinea', phoneCode: '+224', iso2Code: 'GN' },
    { name: 'Guinea-Bissau', phoneCode: '+245', iso2Code: 'GW' },
    { name: 'Ivory Coast', phoneCode: '+225', iso2Code: 'CI' },
    { name: 'Kenya', phoneCode: '+254', iso2Code: 'KE' },
    { name: 'Lesotho', phoneCode: '+266', iso2Code: 'LS' },
    { name: 'Liberia', phoneCode: '+231', iso2Code: 'LR' },
    { name: 'Libya', phoneCode: '+218', iso2Code: 'LY' },
    { name: 'Madagascar', phoneCode: '+261', iso2Code: 'MG' },
    { name: 'Malawi', phoneCode: '+265', iso2Code: 'MW' },
    { name: 'Mali', phoneCode: '+223', iso2Code: 'ML' },
    { name: 'Mauritania', phoneCode: '+222', iso2Code: 'MR' },
    { name: 'Mauritius', phoneCode: '+230', iso2Code: 'MU' },
    { name: 'Morocco', phoneCode: '+212', iso2Code: 'MA' },
    { name: 'Mozambique', phoneCode: '+258', iso2Code: 'MZ' },
    { name: 'Namibia', phoneCode: '+264', iso2Code: 'NA' },
    { name: 'Niger', phoneCode: '+227', iso2Code: 'NE' },
    { name: 'Nigeria', phoneCode: '+234', iso2Code: 'NG' },
    { name: 'Rwanda', phoneCode: '+250', iso2Code: 'RW' },
    { name: 'Sao Tome and Principe', phoneCode: '+239', iso2Code: 'ST' },
    { name: 'Senegal', phoneCode: '+221', iso2Code: 'SN' },
    { name: 'Seychelles', phoneCode: '+248', iso2Code: 'SC' },
    { name: 'Sierra Leone', phoneCode: '+232', iso2Code: 'SL' },
    { name: 'Somalia', phoneCode: '+252', iso2Code: 'SO' },
    { name: 'South Africa', phoneCode: '+27', iso2Code: 'ZA' },
    { name: 'South Sudan', phoneCode: '+211', iso2Code: 'SS' },
    { name: 'Sudan', phoneCode: '+249', iso2Code: 'SD' },
    { name: 'Tanzania', phoneCode: '+255', iso2Code: 'TZ' },
    { name: 'Togo', phoneCode: '+228', iso2Code: 'TG' },
    { name: 'Tunisia', phoneCode: '+216', iso2Code: 'TN' },
    { name: 'Uganda', phoneCode: '+256', iso2Code: 'UG' },
    { name: 'Zambia', phoneCode: '+260', iso2Code: 'ZM' },
    { name: 'Zimbabwe', phoneCode: '+263', iso2Code: 'ZW' },
  ]

export default countries;